# Use containers
sudo: false

language: node_js
  
node_js:
  - "v6.5.0"

addons:
  postgresql: "9.4"
  
services:
  - postgresql
  
test:
  adapter: postgresql
  database: colisee
  username: colisee
  password: colisee

before_script:
  - npm install
  - psql -c 'create database colisee;' -U colisee
  
# Build steps
script:
  - npm test

