# Use containers
sudo: false

language: node_js
node_js:
  - "v6.5.0"

before_script:
  - npm install
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# Build steps
script:
  - npm test

