# Use containers
sudo: false

language: node_js
  
node_js:
  - "v6.5.0"
  
services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - npm install
  - cp config/travis.json config/default.json 
  - psql -c 'create database colisee;' -U postgres
  - psql -U postgres -d colisee -a -f db/init.sql
  
# Build steps
script:
  - npm test

