# Use containers
sudo: required

language: node_js
  
node_js:
  - "v6.9.0"
  
services:
  - docker

before_script:
  - docker-compose build
  - docker-compose up -d

# Build steps
script:
  - docker-compose run --service-ports head-server npm test

