# Use containers
sudo: false

language: node_js
node_js:
  - "v6.5.0"

addons:
  postgresql: "9.4"
  
services:
  - postgresql

before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
  
# Build steps
script:
  - npm test

