version: "2"

services:
  db:
    environment:
      POSTGRES_USER: "colisee"
      POSTGRES_PASSWORD: "colisee"
      POSTGRES_DB: "colisee"
    build: db/
    ports:
      - "5432:5432"

  build-server:
    environment:
      DB_USER: "colisee"
      DB_PASS: "colisee"
      DB_NAME: "colisee"
      DB_HOST: "db"
      DB_PORT: "5432"
    build: build-server/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3002:3000"

  head-server:
    environment:
      DB_USER: "colisee"
      DB_PASS: "colisee"
      DB_NAME: "colisee"
      DB_HOST: "db"
      DB_PORT: "5432"
      HEAD_TOKEN: "abcd"
    build: head-server/
    ports:
      - "3000:3000"

  play-worker:
    environment:
      HEAD_HOST: "head-server"
      HEAD_PORT: "3000"
      HEAD_TOKEN: "abcd"
    build: play-worker/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3000"